name: Download Latest Release

on:
  workflow_dispatch:

jobs:
  download-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get latest release
      id: get_release
      uses: actions/github-release@v1
      with:
        repository: 'metacall/distributable-linux'

    - name: Download release asset
      uses: actions/download-artifact@v3
      with:
        name: metacall-release
        path: ./release
        url: ${{ steps.get_release.outputs.release.assets.find(asset => asset.name === 'metacall-tarball-linux-amd64.tar.gz').browser_download_url }}

    - name: Extract release
      run: |
        tar -xzf ./release/metacall-tarball-linux-amd64.tar.gz
