name: Download Latest MetaCall Tarball

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches: [ main ]

jobs:
  download:
    runs-on: ubuntu-latest  # Use a runner compatible with the architecture

    steps:
      - uses: actions/checkout@v4  # Checkout the repository code

      - name: Get Latest Release Download URL
        run: |
          url=$(curl -sL https://api.github.com/repos/metacall/distributable-linux/releases/latest | jq -r '.assets[] | select(.name == "metacall-tarball-linux-amd64.tar.gz") | .browser_download_url')
          echo "Latest MetaCall tarball URL: $url"
          echo "::set-output name=download_url::$url"  # Store URL as output variable
          wget $url -O metacall-tarball-linux-amd64.tar.gz
