name: Download Latest MetaCall Tarball

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches: [ main ]

jobs:
  LinuxUbuntuRun:
    name: Linux - Ubuntu Run
    runs-on: ubuntu-latest  # Use a runner compatible with the architecture
    steps:
      - uses: actions/checkout@v4  # Checkout the repository code
      - name: Get Latest Release Download
        run: |
          url=$(curl -sL https://api.github.com/repos/metacall/distributable-linux/releases/latest | jq -r '.assets[] | select(.name == "metacall-tarball-linux-amd64.tar.gz") | .browser_download_url')
          wget $url -O metacall-tarball-linux-amd64.tar.gz
          ls -l

  WindowsRun:
    name: Windows Run
    runs-on: windows-latest  # Use a runner compatible with the architecture
    steps:
      - uses: actions/checkout@v4  # Checkout the repository code
      - name: Get Latest Release Download
        shell: pwsh
        run: |
          $releaseUrl = "https://api.github.com/repos/metacall/distributable-linux/releases/latest"
          $assetUrl = (Invoke-RestMethod -Uri $releaseUrl | ConvertFrom-Json).assets | Where-Object { $_.name -eq "metacall-tarball-linux-amd64.tar.gz" } | Select-Object -ExpandProperty browser_download_url
          
          Invoke-WebRequest -Uri $assetUrl -OutFile "metacall-tarball-linux-amd64.tar.gz"
          Get-ChildItem
