name: Download Latest Release

on:
  workflow_dispatch:

jobs:
  download-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get latest release
      id: get_release
      uses: actions/github-release@v1
      with:
        repository: 'metacall/distributable-linux'

    - name: Extract asset URL
      id: extract_asset_url
      run: |
        asset_url=$(echo '${{ steps.get_release.outputs.release.assets.*.browser_download_url }}' | grep 'metacall-tarball-linux-amd64.tar.gz' | head -n 1)
        echo "::set-output name=asset_url::$asset_url"

    - name: Download release asset
      uses: actions/download-artifact@v3
      with:
        name: metacall-release
        path: ./release
        url: ${{ steps.extract_asset_url.outputs.asset_url }}

    - name: Extract release
      run: |
        tar -xzf ./release/metacall-tarball-linux-amd64.tar.gz
