name: Download Latest Release

on:
  workflow_dispatch:

jobs:
  download-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get latest release
      id: get_release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const release = await github.repos.getLatestRelease({
            owner: 'metacall',
            repo: 'distributable-linux'
          });
          const asset = release.data.assets.find(asset => asset.name === 'metacall-tarball-linux-amd64.tar.gz');
          console.log('Asset URL:', asset.browser_download_url);
          return asset.browser_download_url;

    - name: Download release asset
      uses: actions/download-artifact@v3
      with:
        name: metacall-release
        path: ./release
        url: ${{ steps.get_release.outputs.result }}

    - name: Extract release
      run: |
        tar -xzf ./release/metacall-tarball-linux-amd64.tar.gz
