name: Download Latest MetaCall Tarball

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches: [ main ]

jobs:
  LinuxUbuntuRun:
    name: Linux - Ubuntu Run
    runs-on: ubuntu-latest  # Use a runner compatible with the architecture
    steps:
      - uses: actions/checkout@v4  # Checkout the repository code
      
      - name: Get Latest Release Download
        run: |
          sudo apt update
          url=$(curl -sL https://api.github.com/repos/metacall/distributable-linux/releases/latest | jq -r '.assets[] | select(.name == "metacall-tarball-linux-amd64.tar.gz") | .browser_download_url')
          wget $url -O metacall-tarball-linux-amd64.tar.gz

          tar -xvzf metacall-tarball-linux-amd64.tar.gz
          ls
          
      - name: Running Tests
        run: |
          git clone https://github.com/metacall/examples.git
          metacall
  

  WindowsRun:
    name: Windows Run
    runs-on: windows-latest  # Use a runner compatible with the architecture
    steps:
      - uses: actions/checkout@v4  # Checkout the repository code
      
      - name: Get Latest Release Download
        shell: pwsh
        run: |
          $releaseUrl = "https://api.github.com/repos/metacall/distributable-windows/releases/latest"
          $releaseData = Invoke-RestMethod -Uri $releaseUrl -UseBasicParsing -Headers @{"Accept"="application/vnd.github+json"} -SkipHttpErrorCheck
          $assetUrl = $releaseData.assets | Where-Object { $_.name -eq "metacall-tarball-win-x64.zip" } | Select-Object -ExpandProperty browser_download_url
          
          Invoke-WebRequest -Uri $assetUrl -OutFile "metacall-tarball-win-x64.zip"
          dir
          Get-ChildItem
          tar -xf metacall-tarball-win-x64.zip
          dir
          cd metacall-tarball-win-x64
          metacall.bat
          dir
          metacall
          
      - name: Running Tests
        shell: pwsh
        run: |
          git clone https://github.com/metacall/examples.git
          


  MacOSRun:
    name: MacOS Run
    runs-on: macos-latest  # Use a runner compatible with the architecture
    steps:
      - uses: actions/checkout@v4  # Checkout the repository code
      
      - name: Get Latest Release Download
        run: |
          url=$(curl -sL https://api.github.com/repos/metacall/distributable-linux/releases/latest | jq -r '.assets[] | select(.name == "metacall-tarball-linux-amd64.tar.gz") | .browser_download_url')
          wget $url -O metacall-tarball-linux-amd64.tar.gz
          ls -l
          metacall

      - name: Running Tests
        run: |
          git clone https://github.com/metacall/examples.git

