name: Download Latest MetaCall Tarball

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches: [ main ]

jobs:
  LinuxUbuntuRun:
    name: Linux - Ubuntu Run
    runs-on: ubuntu-latest  # Use a runner compatible with the architecture
    steps:
      - uses: actions/checkout@v4  # Checkout the repository code
      
      - name: Get Latest Release Download
        run: |
          sudo apt update
          curl -sL https://raw.githubusercontent.com/metacall/install/master/install.sh | sh

      - name: Running Tests
        run: |
          # git clone https://github.com/metacall/examples.git
          # git clone https://github.com/metacall/examples-testing.git
          cd examples/string-manipulation
          metacall str.rb
  

  WindowsRun:
    name: Windows Run
    runs-on: windows-latest  # Use a runner compatible with the architecture
    steps:
      - uses: actions/checkout@v4  # Checkout the repository code
      
      - name: Get Latest Release Download
        shell: pwsh
        run: |
          powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/metacall/install/master/install.ps1')))"
          dir
          
      - name: Running Tests
        shell: pwsh
        run: |
          git clone https://github.com/metacall/examples.git
          # $current_dir_path = Get-Location
          # echo "$current_dir_path/metacall.bat"
          # cd examples/string-manipulation
          # Start-Process -FilePath "$current_dir_path/metacall.bat" -Wait -NoNewWindow | load rb str.rb
          metacall
          dir

          


  MacOSRun:
    name: MacOS Run
    runs-on: macos-latest  # Use a runner compatible with the architecture
    steps:
      - uses: actions/checkout@v4  # Checkout the repository code
      
      - name: Get Latest Release Download
        run: |
          url=$(curl -sL https://api.github.com/repos/metacall/distributable-linux/releases/latest | jq -r '.assets[] | select(.name == "metacall-tarball-linux-amd64.tar.gz") | .browser_download_url')
          wget $url -O metacall-tarball-linux-amd64.tar.gz
          ls -l
          metacall

      - name: Running Tests
        run: |
          git clone https://github.com/metacall/examples.git

